state_mapper:
  ros__parameters:
    # Order in the following 2 lists is important for mapping
    roboy_link_names:
      [torso,
      upperarm_right,
      lowerarm_right,
      hand_right,
      upperarm_left,
      lowerarm_left,
      hand_left,
      head]
    operator_link_names:
      [chest,
      right_shoulder,
      right_elbow,
      right_wrist,
      left_shoulder,
      left_elbow,
      left_wrist,
      neck]

bullet_roboy:
  ros__parameters:
    parent_link_map:
      torso: torso
      upperarm_right: upperarm_right
      lowerarm_right: lowerarm_right
      elbow_right: lowerarm_right
      hand_right: hand_right
      wrist_right_link1: hand_right
      wrist_right_link2: hand_right
      wrist_right_link: hand_right
      rh_palm: hand_right
      rh_manipulator: hand_right
      rh_ffknuckle: hand_right
      rh_ffproximal: hand_right
      rh_ffmiddle: hand_right
      rh_ffdistal: hand_right
      rh_fftip: hand_right
      rh_mfknuckle: hand_right
      rh_mfproximal: hand_right
      rh_mfmiddle: hand_right
      rh_mfdistal: hand_right
      rh_mftip: hand_right
      rh_rfknuckle: hand_right
      rh_rfproximal: hand_right
      rh_rfmiddle: hand_right
      rh_rfdistal: hand_right
      rh_rftip: hand_right
      rh_lfmetacarpal: hand_right
      rh_lfknuckle: hand_right
      rh_lfproximal: hand_right
      rh_lfmiddle: hand_right
      rh_lfdistal: hand_right
      rh_lftip: hand_right
      rh_thbase: hand_right
      rh_thproximal: hand_right
      rh_thhub: hand_right
      rh_thmiddle: hand_right
      upperarm_left: upperarm_left
      lowerarm_left: lowerarm_left
      elbow_left: lowerarm_left
      hand_left: hand_left
      wrist_left_link1: hand_left
      wrist_left_link2: hand_left
      wrist_left_link: hand_left
      lh_palm: hand_left
      lh_manipulator: hand_left
      lh_ffknuckle: hand_left
      lh_ffproximal: hand_left
      lh_ffmiddle: hand_left
      lh_ffdistal: hand_left
      lh_fftip: hand_left
      lh_mfknuckle: hand_left
      lh_mfproximal: hand_left
      lh_mfmiddle: hand_left
      lh_mfdistal: hand_left
      lh_mftip: hand_left
      lh_rfknuckle: hand_left
      lh_rfproximal: hand_left
      lh_rfmiddle: hand_left
      lh_rfdistal: hand_left
      lh_rftip: hand_left
      lh_lfmetacarpal: hand_left
      lh_lfknuckle: hand_left
      lh_lfproximal: hand_left
      lh_lfmiddle: hand_left
      lh_lfdistal: hand_left
      lh_lftip: hand_left
      lh_thbase: hand_left
      lh_thproximal: hand_left
      lh_thhub: hand_left
      lh_thmiddle: hand_left
      lh_thdistal: hand_left
      lh_thtip: hand_left
      head: head
      head_link2: head
      head_link1: head
      camera_left: head
      camera_right: head

exoforce:
  ros__parameters:
    no_slack_force: 4.0       # (Newtons) Minimal force applied to the tendons to avoid slack
    tendon_init_time: 3.0     # (seconds) Time to wait after starting force controllers to pull the initial slack
    max_force_apply_time: 1.0 # (seconds) Max time the last decomposed force will be applied
    force_decomposition:
      min_tendon_force: 0.5
      max_collision_force: 50.0
    map_link_to_ef:
      left_wrist: [7, 8, 43]
      right_wrist: [4, 5, 3]

operator:
  ros__parameters:
    pull_motor: 16
    pull_force: 30.0
    pull_time: 1.0
    operator_link_dimentions:
      chest:
        [0.24991999999999998,
        0.24991999999999998,
        0.24991999999999992]
      left_elbow:
        [0.09288000000000529,
        0.0928800798163818,
        0.24624002969910885]
      left_shoulder:
        [0.1042400000000326,
        0.10424010023452646,
        0.30872003341150434]
      left_wrist:
        [0.09087999999999999,
        0.09087999999999996,
        0.09088000000000007]
      right_elbow:
        [0.09288000000000397,
        0.09288007981638124,
        0.24624002969910863]
      right_shoulder:
        [0.10424000000003777,
        0.10424010023452582,
        0.30872003341150656]
      right_wrist:
        [0.09087999999999999,
        0.09088000000000002,
        0.09088000000000007]
      neck:
        [0.23287999999999998,
        0.23287999999999998,
        0.23287999999999975]
